apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ingress-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${ADMIN_EMAIL}
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: services-tls
  namespace: dev-tools
spec:
  secretName: services-tls
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  subject:
    organizations:
      - Dev Tools
  commonName: "*.dev-tools.svc.cluster.local"
  dnsNames:
    - "*.dev-tools.svc.cluster.local"
  issuerRef:
    name: ingress-issuer
    kind: ClusterIssuer
