apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ingress-issuer
spec:
  vault:
    server: http://vault.dev-tools.svc.cluster.local:8200
    path: pki/sign/dev-tools
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: dev-tools
        serviceAccountRef:
          name: dev-tools-sa

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: services-tls
  namespace: dev-tools
spec:
  secretName: services-tls
  duration: 1440h # 2 meses
  renewBefore: 168h # 7 días
  subject:
    organizations:
      - Dev Tools
  commonName: "*.dev-tools.svc.cluster.local"
  dnsNames:
    - "*.dev-tools.svc.cluster.local"
  issuerRef:
    name: ingress-issuer
    kind: ClusterIssuer

 # This is a self-signed certificate for the Vault server

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-selfsigned-issuer
  namespace: cert-manager
spec:
  selfSigned: {}

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-ts
  namespace: dev-tools
spec:
  secretName: vault-ts
  duration: 1440h # 2 meses
  renewBefore: 168h # 7 días
  subject:
    organizations:
      - Dev Tools
  commonName: ".dev-tools.svc.cluster.local"
  dnsNames:
    - "*.dev-tools.svc.cluster.local"
  issuerRef:
    name: vault-selfsigned-issuer
    kind: ClusterIssuer
